name: ShoeboxLetters
favicon: null
layout_spectrum: 0.07746806321665645
typography_spectrum: 0.93714380543679
title: Shoebox Letters books
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3779552860651165
  lightness: 0.22342760674655437
  saturation: 0.4351144863758236
  rhythmicContrast: 0.33505179500207305
purpose: []
